language: elixir
elixir:
  - 1.2.6
  - 1.3.1
otp_release:
  - 18.3
  - 19.0
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
