language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.0
otp_release:
  - 18.3
  - 19.3
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
